/* ^^^AUTOGENHEADER^^^ */
#ifndef STREAMSERVICEDELEGATE_H
#define STREAMSERVICEDELEGATE_H

#include <astra_core/capi/astra_types.h>
#include "astra_context.hpp"

namespace astra {

    class stream_service_delegate
    {
    public:
^^^BEGINREPLACE:stream^^^

        static ^RETURN^ ^FUNC^(^PARAMS:void^)
        {
            return static_cast<context*>(^PARAMS:names,voidonly^)->^FUNC^(^PARAMS:names,deref^);
        }
^^^ENDREPLACE^^^
    };
}

#endif /* STREAMSERVICEDELEGATE_H */
