// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FrameDescription.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "FrameDescription.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace sensekit {
namespace serialization {
namespace proto {

namespace {

const ::google::protobuf::Descriptor* FrameDescription_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FrameDescription_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_FrameDescription_2eproto() {
  protobuf_AddDesc_FrameDescription_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "FrameDescription.proto");
  GOOGLE_CHECK(file != NULL);
  FrameDescription_descriptor_ = file->message_type(0);
  static const int FrameDescription_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FrameDescription, frameperiod_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FrameDescription, bufferlength_),
  };
  FrameDescription_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      FrameDescription_descriptor_,
      FrameDescription::default_instance_,
      FrameDescription_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FrameDescription, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FrameDescription, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(FrameDescription));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_FrameDescription_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    FrameDescription_descriptor_, &FrameDescription::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_FrameDescription_2eproto() {
  delete FrameDescription::default_instance_;
  delete FrameDescription_reflection_;
}

void protobuf_AddDesc_FrameDescription_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026FrameDescription.proto\022\034sensekit.seria"
    "lization.proto\"=\n\020FrameDescription\022\023\n\013fr"
    "amePeriod\030\001 \001(\001\022\024\n\014bufferLength\030\002 \001(\r", 117);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "FrameDescription.proto", &protobuf_RegisterTypes);
  FrameDescription::default_instance_ = new FrameDescription();
  FrameDescription::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_FrameDescription_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_FrameDescription_2eproto {
  StaticDescriptorInitializer_FrameDescription_2eproto() {
    protobuf_AddDesc_FrameDescription_2eproto();
  }
} static_descriptor_initializer_FrameDescription_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int FrameDescription::kFramePeriodFieldNumber;
const int FrameDescription::kBufferLengthFieldNumber;
#endif  // !_MSC_VER

FrameDescription::FrameDescription()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:sensekit.serialization.proto.FrameDescription)
}

void FrameDescription::InitAsDefaultInstance() {
}

FrameDescription::FrameDescription(const FrameDescription& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:sensekit.serialization.proto.FrameDescription)
}

void FrameDescription::SharedCtor() {
  _cached_size_ = 0;
  frameperiod_ = 0;
  bufferlength_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FrameDescription::~FrameDescription() {
  // @@protoc_insertion_point(destructor:sensekit.serialization.proto.FrameDescription)
  SharedDtor();
}

void FrameDescription::SharedDtor() {
  if (this != default_instance_) {
  }
}

void FrameDescription::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FrameDescription::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FrameDescription_descriptor_;
}

const FrameDescription& FrameDescription::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_FrameDescription_2eproto();
  return *default_instance_;
}

FrameDescription* FrameDescription::default_instance_ = NULL;

FrameDescription* FrameDescription::New() const {
  return new FrameDescription;
}

void FrameDescription::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<FrameDescription*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(frameperiod_, bufferlength_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool FrameDescription::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sensekit.serialization.proto.FrameDescription)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double framePeriod = 1;
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &frameperiod_)));
          set_has_frameperiod();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_bufferLength;
        break;
      }

      // optional uint32 bufferLength = 2;
      case 2: {
        if (tag == 16) {
         parse_bufferLength:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &bufferlength_)));
          set_has_bufferlength();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sensekit.serialization.proto.FrameDescription)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sensekit.serialization.proto.FrameDescription)
  return false;
#undef DO_
}

void FrameDescription::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sensekit.serialization.proto.FrameDescription)
  // optional double framePeriod = 1;
  if (has_frameperiod()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->frameperiod(), output);
  }

  // optional uint32 bufferLength = 2;
  if (has_bufferlength()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->bufferlength(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:sensekit.serialization.proto.FrameDescription)
}

::google::protobuf::uint8* FrameDescription::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sensekit.serialization.proto.FrameDescription)
  // optional double framePeriod = 1;
  if (has_frameperiod()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->frameperiod(), target);
  }

  // optional uint32 bufferLength = 2;
  if (has_bufferlength()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->bufferlength(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sensekit.serialization.proto.FrameDescription)
  return target;
}

int FrameDescription::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional double framePeriod = 1;
    if (has_frameperiod()) {
      total_size += 1 + 8;
    }

    // optional uint32 bufferLength = 2;
    if (has_bufferlength()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->bufferlength());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FrameDescription::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const FrameDescription* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const FrameDescription*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void FrameDescription::MergeFrom(const FrameDescription& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_frameperiod()) {
      set_frameperiod(from.frameperiod());
    }
    if (from.has_bufferlength()) {
      set_bufferlength(from.bufferlength());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void FrameDescription::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FrameDescription::CopyFrom(const FrameDescription& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FrameDescription::IsInitialized() const {

  return true;
}

void FrameDescription::Swap(FrameDescription* other) {
  if (other != this) {
    std::swap(frameperiod_, other->frameperiod_);
    std::swap(bufferlength_, other->bufferlength_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata FrameDescription::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FrameDescription_descriptor_;
  metadata.reflection = FrameDescription_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace serialization
}  // namespace sensekit

// @@protoc_insertion_point(global_scope)
