// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FrameDescription.proto

#ifndef PROTOBUF_FrameDescription_2eproto__INCLUDED
#define PROTOBUF_FrameDescription_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace astra {
namespace serialization {
namespace proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_FrameDescription_2eproto();
void protobuf_AssignDesc_FrameDescription_2eproto();
void protobuf_ShutdownFile_FrameDescription_2eproto();

class FrameDescription;

// ===================================================================

class FrameDescription : public ::google::protobuf::Message {
 public:
  FrameDescription();
  virtual ~FrameDescription();

  FrameDescription(const FrameDescription& from);

  inline FrameDescription& operator=(const FrameDescription& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FrameDescription& default_instance();

  void Swap(FrameDescription* other);

  // implements Message ----------------------------------------------

  FrameDescription* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FrameDescription& from);
  void MergeFrom(const FrameDescription& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double framePeriod = 1;
  inline bool has_frameperiod() const;
  inline void clear_frameperiod();
  static const int kFramePeriodFieldNumber = 1;
  inline double frameperiod() const;
  inline void set_frameperiod(double value);

  // optional uint32 bufferLength = 2;
  inline bool has_bufferlength() const;
  inline void clear_bufferlength();
  static const int kBufferLengthFieldNumber = 2;
  inline ::google::protobuf::uint32 bufferlength() const;
  inline void set_bufferlength(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:astra.serialization.proto.FrameDescription)
 private:
  inline void set_has_frameperiod();
  inline void clear_has_frameperiod();
  inline void set_has_bufferlength();
  inline void clear_has_bufferlength();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double frameperiod_;
  ::google::protobuf::uint32 bufferlength_;
  friend void  protobuf_AddDesc_FrameDescription_2eproto();
  friend void protobuf_AssignDesc_FrameDescription_2eproto();
  friend void protobuf_ShutdownFile_FrameDescription_2eproto();

  void InitAsDefaultInstance();
  static FrameDescription* default_instance_;
};
// ===================================================================


// ===================================================================

// FrameDescription

// optional double framePeriod = 1;
inline bool FrameDescription::has_frameperiod() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FrameDescription::set_has_frameperiod() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FrameDescription::clear_has_frameperiod() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FrameDescription::clear_frameperiod() {
  frameperiod_ = 0;
  clear_has_frameperiod();
}
inline double FrameDescription::frameperiod() const {
  // @@protoc_insertion_point(field_get:astra.serialization.proto.FrameDescription.framePeriod)
  return frameperiod_;
}
inline void FrameDescription::set_frameperiod(double value) {
  set_has_frameperiod();
  frameperiod_ = value;
  // @@protoc_insertion_point(field_set:astra.serialization.proto.FrameDescription.framePeriod)
}

// optional uint32 bufferLength = 2;
inline bool FrameDescription::has_bufferlength() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FrameDescription::set_has_bufferlength() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FrameDescription::clear_has_bufferlength() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FrameDescription::clear_bufferlength() {
  bufferlength_ = 0u;
  clear_has_bufferlength();
}
inline ::google::protobuf::uint32 FrameDescription::bufferlength() const {
  // @@protoc_insertion_point(field_get:astra.serialization.proto.FrameDescription.bufferLength)
  return bufferlength_;
}
inline void FrameDescription::set_bufferlength(::google::protobuf::uint32 value) {
  set_has_bufferlength();
  bufferlength_ = value;
  // @@protoc_insertion_point(field_set:astra.serialization.proto.FrameDescription.bufferLength)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace serialization
}  // namespace astra

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_FrameDescription_2eproto__INCLUDED
