// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamHeader.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "StreamHeader.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace astra {
namespace serialization {
namespace proto {

namespace {

const ::google::protobuf::Descriptor* StreamHeader_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  StreamHeader_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_StreamHeader_2eproto() {
  protobuf_AddDesc_StreamHeader_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "StreamHeader.proto");
  GOOGLE_CHECK(file != NULL);
  StreamHeader_descriptor_ = file->message_type(0);
  static const int StreamHeader_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StreamHeader, frametype_),
  };
  StreamHeader_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      StreamHeader_descriptor_,
      StreamHeader::default_instance_,
      StreamHeader_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StreamHeader, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StreamHeader, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(StreamHeader));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_StreamHeader_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    StreamHeader_descriptor_, &StreamHeader::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_StreamHeader_2eproto() {
  delete StreamHeader::default_instance_;
  delete StreamHeader_reflection_;
}

void protobuf_AddDesc_StreamHeader_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022StreamHeader.proto\022\034astra.serializa"
    "tion.proto\"!\n\014StreamHeader\022\021\n\tframeType\030"
    "\001 \001(\r", 85);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "StreamHeader.proto", &protobuf_RegisterTypes);
  StreamHeader::default_instance_ = new StreamHeader();
  StreamHeader::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_StreamHeader_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_StreamHeader_2eproto {
  StaticDescriptorInitializer_StreamHeader_2eproto() {
    protobuf_AddDesc_StreamHeader_2eproto();
  }
} static_descriptor_initializer_StreamHeader_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int StreamHeader::kFrameTypeFieldNumber;
#endif  // !_MSC_VER

StreamHeader::StreamHeader()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:astra.serialization.proto.StreamHeader)
}

void StreamHeader::InitAsDefaultInstance() {
}

StreamHeader::StreamHeader(const StreamHeader& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:astra.serialization.proto.StreamHeader)
}

void StreamHeader::SharedCtor() {
  _cached_size_ = 0;
  frametype_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

StreamHeader::~StreamHeader() {
  // @@protoc_insertion_point(destructor:astra.serialization.proto.StreamHeader)
  SharedDtor();
}

void StreamHeader::SharedDtor() {
  if (this != default_instance_) {
  }
}

void StreamHeader::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StreamHeader::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return StreamHeader_descriptor_;
}

const StreamHeader& StreamHeader::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_StreamHeader_2eproto();
  return *default_instance_;
}

StreamHeader* StreamHeader::default_instance_ = NULL;

StreamHeader* StreamHeader::New() const {
  return new StreamHeader;
}

void StreamHeader::Clear() {
  frametype_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool StreamHeader::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:astra.serialization.proto.StreamHeader)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 frameType = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &frametype_)));
          set_has_frametype();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:astra.serialization.proto.StreamHeader)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:astra.serialization.proto.StreamHeader)
  return false;
#undef DO_
}

void StreamHeader::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:astra.serialization.proto.StreamHeader)
  // optional uint32 frameType = 1;
  if (has_frametype()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->frametype(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:astra.serialization.proto.StreamHeader)
}

::google::protobuf::uint8* StreamHeader::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:astra.serialization.proto.StreamHeader)
  // optional uint32 frameType = 1;
  if (has_frametype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->frametype(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:astra.serialization.proto.StreamHeader)
  return target;
}

int StreamHeader::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 frameType = 1;
    if (has_frametype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->frametype());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StreamHeader::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const StreamHeader* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const StreamHeader*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void StreamHeader::MergeFrom(const StreamHeader& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_frametype()) {
      set_frametype(from.frametype());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void StreamHeader::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StreamHeader::CopyFrom(const StreamHeader& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StreamHeader::IsInitialized() const {

  return true;
}

void StreamHeader::Swap(StreamHeader* other) {
  if (other != this) {
    std::swap(frametype_, other->frametype_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata StreamHeader::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = StreamHeader_descriptor_;
  metadata.reflection = StreamHeader_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace serialization
}  // namespace astra

// @@protoc_insertion_point(global_scope)
