// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamHeader.proto

#ifndef PROTOBUF_StreamHeader_2eproto__INCLUDED
#define PROTOBUF_StreamHeader_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace astra {
namespace serialization {
namespace proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_StreamHeader_2eproto();
void protobuf_AssignDesc_StreamHeader_2eproto();
void protobuf_ShutdownFile_StreamHeader_2eproto();

class StreamHeader;

// ===================================================================

class StreamHeader : public ::google::protobuf::Message {
 public:
  StreamHeader();
  virtual ~StreamHeader();

  StreamHeader(const StreamHeader& from);

  inline StreamHeader& operator=(const StreamHeader& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StreamHeader& default_instance();

  void Swap(StreamHeader* other);

  // implements Message ----------------------------------------------

  StreamHeader* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StreamHeader& from);
  void MergeFrom(const StreamHeader& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 frameType = 1;
  inline bool has_frametype() const;
  inline void clear_frametype();
  static const int kFrameTypeFieldNumber = 1;
  inline ::google::protobuf::uint32 frametype() const;
  inline void set_frametype(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:astra.serialization.proto.StreamHeader)
 private:
  inline void set_has_frametype();
  inline void clear_has_frametype();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 frametype_;
  friend void  protobuf_AddDesc_StreamHeader_2eproto();
  friend void protobuf_AssignDesc_StreamHeader_2eproto();
  friend void protobuf_ShutdownFile_StreamHeader_2eproto();

  void InitAsDefaultInstance();
  static StreamHeader* default_instance_;
};
// ===================================================================


// ===================================================================

// StreamHeader

// optional uint32 frameType = 1;
inline bool StreamHeader::has_frametype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StreamHeader::set_has_frametype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StreamHeader::clear_has_frametype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StreamHeader::clear_frametype() {
  frametype_ = 0u;
  clear_has_frametype();
}
inline ::google::protobuf::uint32 StreamHeader::frametype() const {
  // @@protoc_insertion_point(field_get:astra.serialization.proto.StreamHeader.frameType)
  return frametype_;
}
inline void StreamHeader::set_frametype(::google::protobuf::uint32 value) {
  set_has_frametype();
  frametype_ = value;
  // @@protoc_insertion_point(field_set:astra.serialization.proto.StreamHeader.frameType)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace serialization
}  // namespace astra

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_StreamHeader_2eproto__INCLUDED
