#ifndef STREAMTYPES_H
#define STREAMTYPES_H

enum sensekit_core_stream_types {
    SENSEKIT_STREAM_DEPTH = 1,
    SENSEKIT_STREAM_COLOR = 2,
    SENSEKIT_STREAM_HAND = 3,
    SENSEKIT_STREAM_DEBUG_HAND = 3001,
};

#endif /* STREAMTYPES_H */
