/* ^^^AUTOGENHEADER^^^ */
#ifndef SENSEKIT_CAPI_H
#define SENSEKIT_CAPI_H

#include "SenseKit/sensekit_defines.h"
#include "SenseKit/sensekit_types.h"

SENSEKIT_BEGIN_DECLS

SENSEKIT_API sensekit_status_t sensekit_initialize();
SENSEKIT_API sensekit_status_t sensekit_terminate();

^^^BEGINREPLACE:stream^^^
SENSEKIT_API ^RETURN^ sensekit_^FUNC^(^PARAMS^);

^^^ENDREPLACE^^^
SENSEKIT_END_DECLS

#endif /* SENSEKIT_CAPI_H */
