#ifndef HAND_PARAMETERS_H
#define HAND_PARAMETERS_H

enum
{
    SENSEKIT_PARAMETER_DEBUG_HAND_VIEW_TYPE = 0,
    SENSEKIT_PARAMETER_DEBUG_HAND_USE_MOUSE_PROBE = 1,
    SENSEKIT_PARAMETER_DEBUG_HAND_MOUSE_NORM_POSITION = 2,
};

#endif /* HAND_PARAMETERS_H */
