#ifndef IMAGE_PARAMETERS_H
#define IMAGE_PARAMETERS_H

enum {
    SENSEKIT_PARAMETER_IMAGE_HFOV = 0,
    SENSEKIT_PARAMETER_IMAGE_VFOV = 1,
    SENSEKIT_PARAMETER_IMAGE_MIRRORING = 2,
    SENSEKIT_PARAMETER_IMAGE_MODES = 3,
    SENSEKIT_PARAMETER_IMAGE_MODE = 4
};

#endif /* IMAGE_PARAMETERS_H */
