/* ^^^AUTOGENHEADER^^^ */
#include "SenseKitContext.h"
#include "StreamServiceDelegate.h"
#include <Plugins/StreamServiceProxyBase.h>

namespace sensekit {

    static inline StreamServiceProxyBase* create_stream_proxy(SenseKitContext* context)
    {
        StreamServiceProxyBase* proxy = new StreamServiceProxyBase;

^^^BEGINREPLACE:stream^^^
        proxy->^FUNC^ = &StreamServiceDelegate::^FUNC^;
^^^ENDREPLACE^^^
        proxy->streamService = context;

        return proxy;
    }
}
