/* ^^^AUTOGENHEADER^^^ */
#include "SenseKitContext.h"
#include <SenseKit/Plugins/StreamServiceProxyBase.h>
#include <SenseKitAPI.h>
#include "Logging.h"

static sensekit::SenseKitContext g_Context;

INITIALIZE_LOGGING

SENSEKIT_BEGIN_DECLS

^^^BEGINREPLACE:stream^^^
SENSEKIT_API ^RETURN^ sensekit_^FUNC^(^PARAMS^)
{
    return g_Context.^FUNC^(^PARAMS:names,deref^);
}

^^^ENDREPLACE^^^
SENSEKIT_END_DECLS