/* ^^^AUTOGENHEADER^^^ */
#ifndef PLUGINSERVICEPROXY_H
#define PLUGINSERVICEPROXY_H

#include "PluginServiceProxyBase.h"

namespace sensekit {

    class PluginServiceProxy : public PluginServiceProxyBase
    {
    public:
^^^BEGINREPLACE:plugin^^^

    ^RETURN^ ^FUNC^(^PARAMS^)
    {
        return PluginServiceProxyBase::^FUNC^(^PARAMS:void,names^);
    }
^^^ENDREPLACE^^^
    };
}

#endif /* PLUGINSERVICEPROXY_H */
