/* ^^^AUTOGENHEADER^^^ */
#ifndef STREAMSERVICEPROXY_H
#define STREAMSERVICEPROXY_H

#include "StreamServiceProxyBase.h"

namespace sensekit {

    class StreamServiceProxy : public StreamServiceProxyBase
    {
    public:
^^^BEGINREPLACE:stream^^^

        ^RETURN^ ^FUNC^(^PARAMS^)
        {
            return StreamServiceProxyBase::^FUNC^(^PARAMS:void,names^);
        }
^^^ENDREPLACE^^^
    };
}

#endif /* STREAMSERVICEPROXY_H */
