/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orbbec_jni_Astra */

#ifndef _Included_com_orbbec_jni_Astra
#define _Included_com_orbbec_jni_Astra
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_orbbec_jni_Astra
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_orbbec_jni_Astra_initialize
  (JNIEnv *, jclass);

/*
 * Class:     com_orbbec_jni_Astra
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_orbbec_jni_Astra_terminate
  (JNIEnv *, jclass);

/*
 * Class:     com_orbbec_jni_Astra
 * Method:    notify_resource_available
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_orbbec_jni_Astra_notify_1resource_1available
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_orbbec_jni_Astra
 * Method:    notify_resource_unavailable
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_orbbec_jni_Astra_notify_1resource_1unavailable
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
