/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orbbec_jni_SenseKit */

#ifndef _Included_com_orbbec_jni_SenseKit
#define _Included_com_orbbec_jni_SenseKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_orbbec_jni_SenseKit
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_orbbec_jni_SenseKit_initialize
  (JNIEnv *, jclass);

/*
 * Class:     com_orbbec_jni_SenseKit
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_orbbec_jni_SenseKit_terminate
  (JNIEnv *, jclass);

/*
 * Class:     com_orbbec_jni_SenseKit
 * Method:    notify_resource_available
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_orbbec_jni_SenseKit_notify_1resource_1available
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_orbbec_jni_SenseKit
 * Method:    notify_resource_unavailable
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_orbbec_jni_SenseKit_notify_1resource_1unavailable
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
